#set page(width: 170mm, height: auto)

#set table(align: center + horizon)

#table(
    columns: 11,
    table.header(table.cell(colspan: 6, [aWCA]), table.cell(colspan: 5, [expanded-gaussian])),
    [],
    [$epsilon_"c"$],
    [$sigma_"0"$],
    [$r_"0 cut"$],
    [$sigma_"c"$],
    [$r_"c cut"$],
    [],
    [$epsilon_"g"$],
    [$sigma_"g"$],
    [$r_0$],
    [$r_"g,cut"$],
    table.cell(rowspan: 3, [Te-Te]),
    table.cell(rowspan: 3, [1.0]),
    table.cell(rowspan: 3, []),
    table.cell(rowspan: 3, []),
    table.cell(rowspan: 3, []),
    table.cell(rowspan: 3, []),
    [vertex-vertex],
    [1],
    [2],
    [3],
    [5],
    [vertex-facet], [], [], [], [], [facet-facet], [], [], [], [],
    table.cell(rowspan: 4, [Te-Oc]),
    table.cell(rowspan: 4, [1.0]),
    table.cell(rowspan: 4, []),
    table.cell(rowspan: 4, []),
    table.cell(rowspan: 4, []),
    table.cell(rowspan: 4, []),
    [vertex-vertex],
    [1],
    [2],
    [3],
    [5],
    [vertex(Te)-facet(Oc)], [], [], [], [], [vertex(Oc)-facet(Te)], [], [], [], [], [facet-facet], [], [], [], [],
    table.cell(rowspan: 3, [Oc-Oc]),
    table.cell(rowspan: 3, [1.0]),
    table.cell(rowspan: 3, []),
    table.cell(rowspan: 3, []),
    table.cell(rowspan: 3, []),
    table.cell(rowspan: 3, []),
    [vertex-vertex],
    [1],
    [2],
    [3],
    [5],
    [vertex-facet], [], [], [], [], [facet-facet], [], [], [], [],
)
